version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      # PBRP_BRANCH: ''
      VERSION: '3.0.0'
      MAINTAINER: "@I_am_pronoob"
      VENDOR: 'oppo'
      CODENAME: 'CPH1861'
      FLAVOR: 'eng'
      #TEST_BUILD: 'true'
      PB_OFFICIAL: 'true'
      # EXTRA_CMD: ""
      # PB_ENGLISH: 'true'
      CHANGELOG: |
        -Bringup 3.0 
        - Source side changes 
        - Fully Redesigned UI 
        - New Android like Power Menu (Activated via power key hold) 
        - Flashlight toggled by Vol up(+) on hold 
        - Flashlight toggle on Lockscreen 
        - Etc.
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'android-9.0-dev'
          context: org-global
